---
#Debian and Ubuntu
- name: Add MariaDB 11 repository - apt
  block:
    - name: Add repository mariadb GPG keys
      get_url:
        url: https://mariadb.org/mariadb_release_signing_key.pgp
        dest: /etc/apt/trusted.gpg.d/mairadb-repo.gpg
    - name: Add mariadb repository - apt
      apt_repository:
        repo: "deb https://mirror.netcologne.de/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main main/debug"
        state: present
