---
# Debian and Ubuntu
- name: Install required repositories for PHP 8 - apt
  block:
    - name: Add repository ondrej/php for PHP 8
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
      when: ansible_distribution == 'Ubuntu'

    - name: Add repository SURY for PHP 8
      when: ansible_distribution == 'Debian'
      block:
        - name: Add repository SURY GPG keys
          ansible.builtin.get_url:
            url: https://packages.sury.org/php/apt.gpg
            dest: /etc/apt/trusted.gpg.d/sury-repo.gpg
            mode: "0644"
        - name: Add repository SURY for php8.2 Plugins
          ansible.builtin.apt_repository:
            repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
            state: present
