---
- name: apache2 start
  service:
    name: apache2
    state: started
    enabled: true

- name: apache2 stop
  service:
    name: apache2
    state: stopped
    enabled: false

- name: apache2 restart
  service:
    name: apache2
    state: restarted
    enabled: true
