---
- name: Service apache2 start
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Service apache2 stop
  ansible.builtin.service:
    name: apache2
    state: stopped
    enabled: false

- name: Service apache2 restart
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true
