---
- name: httpd start
  service:
    name: httpd
    state: started
    enabled: true

- name: httpd stop
  service:
    name: httpd
    state: stopped
    enabled: false

- name: httpd restart
  service:
    name: httpd
    state: restarted
    enabled: true
