---
- name: mysql start
  service:
    name: mariadb
    state: started
    enabled: true

- name: mysql stop
  service:
    name: mariadb
    state: stopped
    enabled: false

- name: mysql restart
  service:
    name: mariadb
    state: restarted
    enabled: true