---
- name: Service mysql start
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Service mysql stop
  ansible.builtin.service:
    name: mariadb
    state: stopped
    enabled: false

- name: Service mysql restart
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: true