---
- name: nginx start
  service:
    name: nginx
    state: started
    enabled: true

- name: nginx stop
  service:
    name: nginx
    state: stopped
    enabled: false

- name: nginx restart
  service:
    name: nginx
    state: restarted
    enabled: true