---
- name: php-fpm-deb start
  service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: true

- name: php-fpm-deb stop
  service:
    name: "php{{ php_version }}-fpm"
    state: stopped
    enabled: false

- name: php-fpm-deb restart
  service:
    name: "php{{ php_version }}-fpm"
    state: restarted
    enabled: true
