---
- name: Service php-fpm-deb start
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: true

- name: Service php-fpm-deb stop
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: stopped
    enabled: false

- name: Service php-fpm-deb restart
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted
    enabled: true
