---
- name: php-fpm start
  service:
    name: php-fpm
    state: started
    enabled: true

- name: php-fpm stop
  service:
    name: php-fpm
    state: stopped
    enabled: false

- name: php-fpm restart
  service:
    name: php-fpm
    state: restarted
    enabled: true
