---
- name: Service php-fpm start
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: true

- name: Service php-fpm stop
  ansible.builtin.service:
    name: php-fpm
    state: stopped
    enabled: false

- name: Service php-fpm restart
  ansible.builtin.service:
    name: php-fpm
    state: restarted
    enabled: true
