---
- name: Service zabbix-agent start
  ansible.builtin.service:
    name: zabbix-agent
    state: started
    enabled: true

- name: Service zabbix-agent stop
  ansible.builtin.service:
    name: zabbix-agent
    state: stopped
    enabled: false

- name: Service zabbix-agent restart
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: true
