---
- name: zabbix-agent start
  service:
    name: zabbix-agent
    state: started
    enabled: true

- name: zabbix-agent stop
  service:
    name: zabbix-agent
    state: stopped
    enabled: false

- name: zabbix-agent restart
  service:
    name: zabbix-agent
    state: restarted
    enabled: true
