---
- name: Service zabbix-server start
  ansible.builtin.service:
    name: zabbix-server
    state: started
    enabled: true

- name: Service zabbix-server stop
  ansible.builtin.service:
    name: zabbix-server
    state: stopped
    enabled: false

- name: Service zabbix-server restart
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: true
