---
- name: zabbix-server start
  service:
    name: zabbix-server
    state: started
    enabled: true

- name: zabbix-server stop
  service:
    name: zabbix-server
    state: stopped
    enabled: false

- name: zabbix-server restart
  service:
    name: zabbix-server
    state: restarted
    enabled: true
