---
# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  pull_request:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required ansible collections
        run: ansible-galaxy install -r requirements.yml # Install required collections to resolve related warnings on ansible-lint
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
